### ISSUE TITLE
Please fix iOS Yellow box warning RNCallKit requires main queue setup since it overrides `init`

### ISSUE THREAD

**Issue by bob76828** [wazo-pbx/react-native-callkeep#29]
Reference https://github.com/ianlin/react-native-callkit/pull/63

**Comment by manuquentin** [comment]
Hi @bob76828 
Your issue is already fixed by #19 

I've just published a version `2.0.1` on npm. Can you tell me if you still have the issue ?

**Comment by bob76828** [comment]
@manuquentin It's fixed. Thx!!
